language: java
sudo: false
jdk: oraclejdk9
services:
  - docker
before_install:
  - docker version
  - docker info
install:
  - mvn clean test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify
after_success:
  - mvn coveralls:report -q
